### ISSUE TITLE
 OneLogin::RubySaml::ValidationError (Issuer of the Assertion not found or multiple.):

### ISSUE THREAD

**Issue by mostafaSYR** [apokalipto/devise_saml_authenticatable#117]
hi there, 
thanks for the gem, its pretty useful. However, I get an error , with reading the response, 
despite having a clear "<Issuer xmlns=\"urn:oasis:names:tc:SAML:2.0:assertion\">https://corp-sts-stage.vodafone.com/adfs/services/trust"  one tag.
although
when I inspect the parsed reponse, it seems that response.response = <UNDEFINED> ... </>>, is that noraml?!! 

thanks in advance :) .

**Comment by mostafaSYR** [comment]
actullay, document in my case is "<UNDEFINED> ... </>", does ithat look normal ?!!

**Comment by mostafaSYR** [comment]
anyway  Im getting a '[ ]' as output of this request

**Comment by adamstegman** [comment]
I can't remember the appropriate top-level tag of a SAML response off the top of my head, but UNDEFINED definitely seems wrong!

**Comment by mostafaSYR** [comment]
Hey,
it seems that the Idp didnt handle the request properly.
anyway, it is running right now. 
thanx a lot for this awesome gem 😄

**Comment by aneziocampos** [comment]
@mostafaSYR I'm having the same issue with an ADFS, what did they change to make it work?

**Comment by maazulhaque** [comment]
@mostafaSYR How did you resolve this? I am having the same issue where document is undefined. Is that a one login issue or do I have to do something on my end ?

**Comment by mattbaumann1** [comment]
This seems to still be an issue for me also. The error seems to be in the devise_saml_authenticatable/lib/devise_saml_authenticatable/default_idp_entity_id_reader.rb. This only sorts into request and response, but when a SP initiated logout happens, it sends back a LogoutResponse instead of a response. The ruby-saml gem processes these two differently so the default_idp_entity_id_reader  needs to have a third option to create a  OneLogin::RubySaml::LogoutResponse.new. If it doesn't, it tries to create a response and it doesn't have the right attributes to do so. I experimented with it a little bit but couldn't get it to work.

**Comment by mattbaumann1** [comment]
I might have been incorrect. It looks like this all needs to be handled by building out controller actions and views from the Single Log Out section of the ruby-saml gem readme. Is this being handled by this gem?

**Comment by adamstegman** [comment]
We handle SP-initiated logout using `Devise::SamlSessionsController#destroy` which is inherited from `Devise::SessionsController#destroy`. That logs the user out using Devise's `sign_out` method, then [redirects to the IdP using a `LogoutRequest`](https://github.com/apokalipto/devise_saml_authenticatable/blob/f310efdf49f4010b7ce47eb08eb75f3dc016b3e5/app/controllers/devise/saml_sessions_controller.rb#L57) so that the user is also logged out of the IdP.

So it seems a little different from what the ruby-saml README talks about—it doesn't log a user out until a `LogoutResponse` is received. 

I'm trying to understand what the real difference is, and it seems like in the latter case, the one suggested by ruby-saml, the user ends up back at the SP's login page instead of being left at the IdP's login page. Is that accurate? What is happening for you?

**Comment by mattbaumann1** [comment]
Thanks again for your quick response and being patient with my working through this. I am still trying to navigate through this and making sense of it as I go. Ultimately the problem we are having is that we can't process the LogoutResponse returned from the IDP, what we are realizing is that maybe we don't need to. Thank you again.

**Comment by adamstegman** [comment]
Just out of curiosity, are you getting an error? Even if we don't need to do anything, it would be good to handle valid responses so that there aren't any errors being raised by the gem.

**Comment by mattbaumann1** [comment]
So I think I was totally wrong in my comment above, but we did find a fix for it here. I need to do a little cleanup but might set up a PR. 

The errors that I was getting were a combination of "OneLogin::RubySaml::ValidationError (Issuer of the Assertion not found or multiple.)" on the Issuers and Assertions coming out of ruby-saml. Ultimately we fixed this by writing a custom DefaultIdpEntityIdReader and then using the devise initializer to point to ours instead of the one here. We needed to split responses between a Response and a LogoutResponse, because issuers can't be called on a LogoutResponse.

**Comment by mattbaumann1** [comment]
`module DeviseSamlAuthenticatable
  class CompetitionsIdpEntityIdReader
    def self.entity_id(params)
      if params[:SAMLRequest]
        OneLogin::RubySaml::SloLogoutrequest.new(
          params[:SAMLRequest],
          settings: Devise.saml_config,
          allowed_clock_drift: Devise.allowed_clock_drift_in_seconds,
        ).issuer
      elsif params[:SAMLResponse]
        response = OneLogin::RubySaml::Response.new(params[:SAMLResponse],
            settings: Devise.saml_config,
            allowed_clock_drift: Devise.allowed_clock_drift_in_seconds,
          )
        doc = REXML::Document.new(response.response)

        if REXML::XPath.match(doc,"/p:LogoutResponse",{ "p" => OneLogin::RubySaml::SamlMessage::PROTOCOL}).any?
          REXML::XPath.match(doc,"/p:LogoutResponse/a:Issuer",{ "p" => OneLogin::RubySaml::SamlMessage::PROTOCOL, "a" => OneLogin::RubySaml::SamlMessage::ASSERTION }).first.text
        else
          response.issuers.first
        end
      end
    end
  end
end`

**Comment by mattbaumann1** [comment]
I just wanted to throw this up in case it could help someone because it might take me a bit to create a PR. Also I have been having trouble posting a block of code and want to just throw it up quickly, so here it is.

`module DeviseSamlAuthenticatable
  class CompetitionsIdpEntityIdReader
    def self.entity_id(params)
      if params[:SAMLRequest]
        OneLogin::RubySaml::SloLogoutrequest.new(
          params[:SAMLRequest],
          settings: Devise.saml_config,
          allowed_clock_drift: Devise.allowed_clock_drift_in_seconds,
        ).issuer
      elsif params[:SAMLResponse]
        response = OneLogin::RubySaml::Response.new(params[:SAMLResponse],
            settings: Devise.saml_config,
            allowed_clock_drift: Devise.allowed_clock_drift_in_seconds,
          )
        doc = REXML::Document.new(response.response)

        if REXML::XPath.match(doc,"/p:LogoutResponse",{ "p" => OneLogin::RubySaml::SamlMessage::PROTOCOL}).any?
          REXML::XPath.match(doc,"/p:LogoutResponse/a:Issuer",{ "p" => OneLogin::RubySaml::SamlMessage::PROTOCOL, "a" => OneLogin::RubySaml::SamlMessage::ASSERTION }).first.text
        else
          response.issuers.first
        end
      end
    end
  end
end`

**Comment by maheshm** [comment]
I have the same issue, but it happens during the sign-in for me. I am getting this error when trying to access `@current_user` after login. @mattbaumann1 the code that you have here will fix it?

**Comment by mattbaumann1** [comment]
See issue 151 above. I am not sure if it is the same issue, but there are a couple of things that we needed to do. You need to be on the master branch here so that you can save the session index. There are a few other things we did to get this to work. We didn't want to store the session index in the DB, because there are issues if someone logs in from two different browsers. We stored the attribute on the user. So if you are on the master branch, I think this is the rest of what we did to get it to work. I have been meaning to put together a pull request for the gem, but haven't had a chance yet. I think that this would beneficial for others if they are initiating an IDP logout that requires a session index.

/config/initializers/devise.rb

```
  # Optional. This stores the session index defined by the IDP during login.  If provided it will be used as a salt
  # for the user's session to facilitate an IDP initiated logout request.
  config.saml_session_index_key = :session_index
```


/models/user.rb

```
attr_accessor Devise.saml_session_index_key.to_sym
  # https://github.com/apokalipto/devise_saml_authenticatable/issues/151
  def authenticatable_salt
    self.read_attribute(Devise.saml_session_index_key.to_sym) if self.read_attribute(Devise.saml_session_index_key.to_sym).present?
  end
```


And then finally we added some methods to the controller.
/controllers/saml_sessions_controller.rb

```
# require "ruby-saml"

class SamlSessionsController < Devise::SamlSessionsController
  after_action :set_saml_session_index_on_session, only: :create
  skip_before_action :verify_authenticity_token, raise: false
  prepend_before_action :store_info_for_sp_initiated_logout, only: :destroy
  prepend_before_action :set_saml_session_index_on_current_user, only: :destroy

  protected

  def set_saml_session_index_on_session
    session[Devise.saml_session_index_key] = current_user.send(Devise.saml_session_index_key) if user_signed_in?
  end

  def set_saml_session_index_on_current_user
    current_user.update_attribute(Devise.saml_session_index_key, session[Devise.saml_session_index_key])
  end
end
```

**Comment by kcollignon** [comment]
@maheshm did you ever get this resolved? I am having same issue on sign-in

**Comment by mattbaumann1** [comment]
@kcollignon We were able to get this fixed by overwriting things locally. See my comment above and on issue #151. I had intended to write this up and create a PR, but I got pulled in a different direction at work.

**Comment by kcollignon** [comment]
@mattbaumann1 yes their response comes back and it looks valid to me. However, if I run the following code:

```
res = OneLogin::RubySaml::Response.new(
        params[:SAMLResponse],
        settings: Devise.saml_config,
        allowed_clock_drift: Devise.allowed_clock_drift_in_seconds,
      ).issuers
```

That is when it throws the error `Issuer of the Assertion not found or multiple`

If I look at the res object before calling the .issuers method I can see the response XML and the issuer tag in it
