### ISSUE TITLE
Invalid Signature on SAML Response

### ISSUE THREAD

**Issue by kcollignon** [apokalipto/devise_saml_authenticatable#168]
Hello,

I have a campus Idp that I am trying to authenticate against. Using SAML Tool and other means, I have confirmed that the EntityID, cert fingerprint, and details are configured correctly. However after a successful login on the IdP, I am getting the following response in my Rails logs. 

Would you have any areas where I should look to troubleshoot this specific message?

`Invalid Signature on SAML Response`

**Comment by mattbaumann1** [comment]
This issue is closed, but it didn't have an answer. I know that we were dealing with this recently and we were having trouble with the IDP not sending a signature because our security setting from ruby-saml for want_assertion_signed needed to be changed to true. 

We are also having trouble on sign outs with older versions of Safari truncating the SAMLRequest to the IDP. I still haven't figured this one out. It works in other browsers and with new versions of Safari.

**Comment by kcollignon** [comment]
@mattbaumann1 do you know if there is a way to override the Devise SAML Resource locator per IDP? (when using multiple) ? 

I modified my IDP Settings adapter to set the right entity ID, like so:

```
when "school1"
      Devise.saml_create_user = false
      Devise.saml_update_user = false
      Devise.saml_resource_locator = Proc.new do |model, saml_response, auth_value|
        model.where(unique_id: auth_value)).first
      end
when "school2"
      Devise.saml_create_user = false
      Devise.saml_update_user = false
```

However it looks like it still applies to EVERY user that authenticates and not just that specific IdP

**Comment by mattbaumann1** [comment]
That is different than what we needed to do. I have never had to deal with the saml_resource_locator. Interesting. We only have one IDP, but as I am looking at the new configurable attribute-map, I am looking at the IDP settings adapter. 

Thanks for sharing.
