### ISSUE TITLE
saml_session_index_key breaks database authentication

### ISSUE THREAD

**Issue by adamstegman** [apokalipto/devise_saml_authenticatable#22]
We are currently using SAML SSO at the same time as database authentication while we migrate users to our SSO solution.

We discovered that users who had signed in via SSO were unable to use database authentication anymore (specifically for OAuth token access) because the `saml_session_index_key` configuration had overridden the `#authenticatable_salt` method in our model to implement asynchronous IdP-initiated logout. The salt used to compare passwords no longer matched the one generated at the time of registration.

We're going to dig into devise to see if there is another way to implement asynchronous logout without affecting database authentication.

**Comment by hammady** [comment]
In my case when I include the strategies in the following order, it works as expected:
```ruby
devise :database_authenticatable, ..., :saml_authenticatable
```
The reason is that chained modules refer to previous modules as their `super`, so the current implementation would return the session index from `saml_authenticatable` if it is not empty. Otherwise, it calls `super` which hits the salt defined in the `database_authenticatable`.
Does this work for you @adamstegman ?

**Comment by adamstegman** [comment]
Oh, nice catch. We're years past this transition point (and no longer use this gem internally), so I'm unable to test. But I'll close this issue with this solution, thank you!
