### ISSUE TITLE
Complex attributes

### ISSUE THREAD

**Issue by netpenthe** [apokalipto/devise_saml_authenticatable#30]
I am trying to have SAML + database, I have seen issue #25 

I want to have complex attributes, for example:
- my setup requires a unique email address but some uses in the IDP do not have email address
- the IDP has "first name" and "last name" and my devise setup only has "name"

To get this done I want to change "/devise_saml_authenticatable/model.rb".

What is the best way for me to create my own version of model.rb, to override the one in the gem?

(Is there a better way to do this?)

**Comment by adamstegman** [comment]
> my setup requires a unique email address but some uses in the IDP do not have email address

I assume that's not your IdP's subject then.

So you have one attribute that may or may not be present, and two attributes that need to be combined. It sounds like you'd need to re-open the `Model` class and redefine `set_user_saml_attributes(user,attributes)`.

If you can think of a nice generic way to do this, please do open a PR.

I'm not sure off the top of my head how to approach this as part of the gem—if an attribute is missing or empty, it may need to be erased in the DB rather than just skipped. I think maybe the `Model` class just needs to be more extensible.

**Comment by netpenthe** [comment]
@adamstegman  thanks for that, i thought that is what i'd have to do.
