### ISSUE TITLE
Documentation on idp.yml

### ISSUE THREAD

**Issue by martinverdejo** [apokalipto/devise_saml_authenticatable#39]
Do we have documentation or example on how to configure idp.yml? I'm new to SAML, SSO, and federated identity management. Here's my original question: http://stackoverflow.com/questions/35007745/devise-saml-authenticatable-response-does-not-contain-attributes

**Comment by adamstegman** [comment]
I also posted this on that SO question:

The [usage section](https://github.com/apokalipto/devise_saml_authenticatable#usage) of the README has the configuration for the gem. The `saml_config` is filled out in the `config.saml_configure` section, which just gives you the `RubySaml::Settings` object to configure (as described in the [ruby-saml](https://github.com/onelogin/ruby-saml#the-initialization-phase) documentation).

So you'll want a file called `config/initializers/devise.rb` with:

    config.saml_configure do |settings|
      settings.assertion_consumer_service_url = "http://localhost:3000/users/saml/auth"
      # more consumer configuration here
    end

**Comment by mathieujobin** [comment]
does it support connecting to multiple IDPs ?

**Comment by adamstegman** [comment]
The IdP support is implemented through onelogin/ruby-saml, so that's where you'd find that sort of documentation. I found onelogin/ruby-saml#165 which is pretty clear that multiple IdP support is not part of the roadmap. It does briefly discuss a possible approach to support for multiple IdPs if you're interested in doing it anyway.
