### ISSUE TITLE
Question about `Devise::Strategies::SamlAuthenticatable#valid?` method

### ISSUE THREAD

**Issue by mathildemouw** [apokalipto/devise_saml_authenticatable#49]
Hi! We are working on a PR that would add [multiple IdP support](https://github.com/apokalipto/devise_saml_authenticatable/issues/44) out-of-the-box to devise_saml_authenticatable and ran into a question about how the `Devise::Strategies::SamlAuthenticatable#valid?` method should behave. I'm not sure we've fully grasped what makes a valid or invalid strategy after reading this method. 

We were wondering about the significance of the `OneLogin::RubySaml::Logoutresponse` on line 9 in lib/devise_sam_authenticatable/strategy.rb. Why do we need to check that the Logoutresponse's `#response` does not return the string 'Logoutresponse' in order to determine if the strategy is valid? We thought that perhaps you were using `OneLogin::RubySaml::Logoutresponse` in order to allow ruby-saml to decode the SAMLResponse, but we weren't sure.

Thank you in advance for helping! We will be opening our pull request shortly. Adding the appropriate behavior to `Devise::Strategies::SamlAuthenticatable#valid?` for our multiple IdP feature is one of our last remaining steps!

**Comment by tooluser** [comment]
Howdy! I'm working with @mathildemouw on this. 

The method in question is this, on the `SamlAuthenticatable` strategy:

```ruby
def valid?
  if params[:SAMLResponse]
    response = OneLogin::RubySaml::Logoutresponse.new(params[:SAMLResponse], saml_config)
    !(response.response.include? 'LogoutResponse')
  else
    false
  end
end
```

It _looks_ like generation of a `LogoutResponse` is just a quick way to take advantage of that classes base64 decoding. No other validation (e.g. of the IdP) is performed in generating the response. Does that sound reasonable? All tests pass when it is modified to not pass `saml_config`, which fits because AFAICT it doesn't use any specific settings. 

Code inspection suggests this is a good guess, but the line:
```ruby
!(response.response.include? 'LogoutResponse')
``` 

gives pause - it very specifically checks to be sure the response _does not_ include LogoutResponse - so I thought we may be missing something. 

Thanks a million for any light you can shine.

**Comment by adamstegman** [comment]
Sorry for the late response. I was trying to see if @mitch-lindsay remembered why he put that particular check in. It sounds like checking `#is_valid?` is the right way to go, it's just that `LogoutResponse` doesn't have that method. Maybe this check is just incomplete and `#is_valid?` should be used if it's not a logout response.

**Comment by tooluser** [comment]
@adamstegman That makes sense. Thanks a million for the response. We've made the initial change, at least, and others may come, and we're now unblocked. 

Thanks again!

**Comment by mitch-lindsay** [comment]
The initial solution looks fairly close to what you're recommending @tooluser  (2972cdd80dbb3ee57c1951920cb2ba13e88ffeb1)
I tried extensively today to reproduce the specific case that prompted me to change the solution (5beba7a2187e820a01ed4cb508526abc24e606ef) but I couldn't generate the problem again.  Maybe it was a weird case in our IdP but it seems to be resolved at this time.  That being the case, it should be fine to validate with ```OneLogin::RubySaml::Response```

**Comment by tooluser** [comment]
Excellent! Thanks, it'll be in the PR! 

> view it on GitHub, or mute the thread.
