### ISSUE TITLE
IDP Initiated Post

### ISSUE THREAD

**Issue by alanruth** [apokalipto/devise_saml_authenticatable#55]
Our scenario is that the user will be logged into the idp and then click on a link. This link will post the response to our application. We will then authenticate the user with the attribute passed to us (email) and if found, we want to log them into the application.

The response is being posted to users/saml/auth and this is where the logic finds the user. However what appears to be happening next is that it attempts to redirect to the idp using the AuthnRequest.

How can we just accept the response to users/saml/auth, authenticate and then log them in?

Appreciate any help.

**Comment by adamstegman** [comment]
That sounds like the correct workflow, but your user isn't being found by the model helpers. It sounds like the user's email would be contained in an attribute instead of the subject, so does the SAML response being sent by your IdP contain attributes that are mapped in your `attribute-map.yml` to the appropriate column?

It might be helpful to inject some logging into the [gem's model code](https://github.com/apokalipto/devise_saml_authenticatable/blob/master/lib/devise_saml_authenticatable/model.rb#L31) and peek at the SAML response being used, and make sure it matches what you expect.
