### ISSUE TITLE
RSPEC controller tests

### ISSUE THREAD

**Issue by taylor01** [apokalipto/devise_saml_authenticatable#84]
I may be missing something, but how do I run RSPEC controller tests?  I'm running into issues where I can't authenticate the controller actions since there is no mechanism to have a database authenticated user.

Do I have to mock-up the SAML authentication for the tests?

I end up with these types of errors in my tests.

```  32) ServiceHistoriesController DELETE #destroy redirects to the service_histories list
      Failure/Error: @user = FactoryGirl.create(:user)

      NoMethodError:
        undefined method `password=' for #<User:0x007ff6f8f53c68>
        Did you mean?  password
      # ./spec/controllers/service_histories_controller_spec.rb:23:in `block (2 levels) in <top (required)>'
      # ./spec/spec_helper.rb:108:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:107:in `block (2 levels) in <top (required)>'```

**Comment by adamstegman** [comment]
- in this case, the error is that your user factory is attempting to set a password. It shouldn't do that, because `User` doesn't have a password.
- unless you're specifically testing the login workflow, you should use the `sign_in` devise helper before your test: https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-3-and-4-(and-RSpec)#controller-specs
- if you want to acceptance test the login workflow, yes, you should mock up SAML authentication. I've done this by using [ruby-saml-idp](https://github.com/lawrencepit/ruby-saml-idp) to spin up an IdP server process.

**Comment by taylor01** [comment]
oh.  duh.  that makes complete sense.  Not sure how I missed that.  Thanks for the help.
